# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s1GeFyUeSSn39JpESMbNg8aMeMZQrXU9
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load and clean
# To upload your file, click the folder icon on the left sidebar, then click the 'Upload to session storage' icon.
# After uploading, replace 'your_file.csv' with the actual filename.
df = pd.read_csv('/content/Motor_Vehicle_Collisions_-_Crashes_20260202.csv')
df['hour'] = df['CRASH TIME'].str.split(':').str[0].astype(int)

# Aggregate and Plot
hourly_data = df.groupby('hour').size()
hourly_data.plot(kind='bar', color='skyblue', title='Crashes by Hour')
plt.xlabel('Hour (24h)')
plt.ylabel('Total Collisions')
plt.savefig('nyc_crash_trend.png')