SELECT 
    "CONTRIBUTING FACTOR VEHICLE 1", 
    SUM("NUMBER OF PERSONS INJURED") AS total_injuries
FROM "Motor_Vehicle_Collisions_-_Crashes_20260202"
WHERE "CONTRIBUTING FACTOR VEHICLE 1" != 'Unspecified'
GROUP BY "CONTRIBUTING FACTOR VEHICLE 1"
ORDER BY total_injuries DESC
LIMIT 5;